export const ROUTES = {
      HOME: "/",
      LOGIN: "/login",
      REGISTER: "/register",
      VERIFY_EMAIL: "/verify-email",
      FORGOT_PASSWORD: "/forgot-password",
      RESET_PASSWORD: "/reset-password",
      SELECT_ROLE: "/select-role",
      ACCOUNT: "/account",
      SEARCH: "/search",
      CART: "/cart",
      CHECKOUT: "/checkout",
      ORDER_SUCCESS: "/ordersuccess",
      COD_ORDER_SUCCESS: "/order-success/:orderId",
      PAYMENT_SUCCESS: "/payment-success/:paymentId",
      ADDRESS: "/address",
      ORDERS: "/orders",
      ORDER_DETAILS: "/orders/:id",
      ABOUT: "/about",
      HELP: "/help",
      PRIVACY: "/privacy",
      TERMS: "/terms",
      REFUNDS: "/refunds",
      BLOG: "/blog",
      CONTACT: "/contact",
      FAQ: "/faq",

      SELLER: "/seller",
      RESTAURANT_ID: "/restaurant/:id",

      RIDER: {
            ROOT: "/rider",
            DASHBOARD: "/rider/dashboard",
            ORDERS: "/rider/orders",
            ORDER_DETAILS: "/rider/orders/:id",
            EARNINGS: "/rider/earnings",
            WALLET: "/rider/wallet",
            PROFILE: "/rider/profile",
            DOCUMENTS: "/rider/documents",
            SETTINGS: "/rider/settings",
      },

      ADMIN: {
            LOGIN: "/admin/login",
            DASHBOARD: "/admin/dashboard",
            USERS: "/admin/users",
            RESTAURANTS: "/admin/restaurants",
            RIDERS: "/admin/riders",
            ORDERS: "/admin/orders",
            ANALYTICS: "/admin/analytics",
            COUPONS: "/admin/coupons",
            REVIEWS: "/admin/reviews",
      }
};
